// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: main.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package vos.lsp;

@kotlin.jvm.JvmName("-initializehelloRequest")
public inline fun helloRequest(block: vos.lsp.HelloRequestKt.Dsl.() -> kotlin.Unit): vos.lsp.Main.HelloRequest =
  vos.lsp.HelloRequestKt.Dsl._create(vos.lsp.Main.HelloRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 * The request message containing the user's name.
 * ```
 *
 * Protobuf type `vos.lsp.HelloRequest`
 */
public object HelloRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: vos.lsp.Main.HelloRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: vos.lsp.Main.HelloRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): vos.lsp.Main.HelloRequest = _builder.build()

    /**
     * `string name = 1;`
     */
    public var name: kotlin.String
      @JvmName("getName")
      get() = _builder.getName()
      @JvmName("setName")
      set(value) {
        _builder.setName(value)
      }
    /**
     * `string name = 1;`
     */
    public fun clearName() {
      _builder.clearName()
    }
  }
}
@kotlin.jvm.JvmSynthetic
@com.google.errorprone.annotations.CheckReturnValue
public inline fun vos.lsp.Main.HelloRequest.copy(block: vos.lsp.HelloRequestKt.Dsl.() -> kotlin.Unit): vos.lsp.Main.HelloRequest =
  vos.lsp.HelloRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

